### ISSUE TITLE
Refresh benchmark results

### ISSUE THREAD

**Issue by valyala** [SlinSo/goTemplateBenchmark#4]
It would be great periodically refreshing benchmark results after `go get -u` and `go generate` for all the template engines, since they may be modified sometimes.

Additionally, it would be great to see results fo `go 1.8` which should be released today.

**Comment by SlinSo** [comment]
Hi @valyala ,
results are updated to go 1.8.

I've updated the shell scripts, so its more obvious that I did update the dependencies and template generation.
