### ISSUE TITLE
Missing bytes.Buffer.Reset in certain benchmarks

### ISSUE THREAD

**Issue by valyala** [SlinSo/goTemplateBenchmark#5]
It looks like certain benchmarks don't reset `bytes.Buffer` after each iteration, so the buffer constantly grows during the benchmark.

**Comment by SlinSo** [comment]
Hi @valyala ,

thanks for spotting this. There were a lot of test cases where I did not reset the buffer. Especially the fastest engines like "quicktemplate" have gain a lot from resetting the buffer. a lot less memory to handle for the runtime :) almost 30% performance gained.
